### ISSUE TITLE
Argument list too long to launch Firefox Binary with profile

### ISSUE THREAD

**Issue by parmegv** [webfp/tor-browser-crawler#25]
2016-04-27 05:19:17,400 -                     INFO - Dumpcap killed. Capture size: 525361 Bytes /home/ubuntu/tor-browser-crawler/results/160426_075313/1_22_17/capture.pcap
2016-04-27 05:19:25,485 -                     INFO - Filtering packets without a guard IP.
2016-04-27 05:19:26,347 -                     INFO - **\* Visit #8 to http://rediff.com ***
2016-04-27 05:19:31,908 -                     INFO - dumpcap -P -a duration:120 -a filesize:40000 -i eth0 -s 0 -f 'tcp and not host 127.0.0.1 and not tcp port 22 and not tcp port 20' -w /home/ubuntu/tor-browser-crawler/results/160426_075313/1_22_18/capture.pcap
2016-04-27 05:19:42,790 -                     INFO - Dumpcap killed. Capture size: 492334 Bytes /home/ubuntu/tor-browser-crawler/results/160426_075313/1_22_18/capture.pcap
2016-04-27 05:19:50,525 -                     INFO - Filtering packets without a guard IP.
2016-04-27 05:19:51,287 -                     INFO - **\* Visit #9 to http://rediff.com ***
Traceback (most recent call last):
  File "./bin/tbcrawler.py", line 16, in <module>
    run()
  File "/home/ubuntu/tor-browser-crawler/tbcrawler/pytbcrawler.py", line 68, in run
    crawler.crawl(job)
  File "/home/ubuntu/tor-browser-crawler/tbcrawler/crawler.py", line 28, in crawl
    self.**do_batch()
  File "/home/ubuntu/tor-browser-crawler/tbcrawler/crawler.py", line 45, in __do_batch
    self.__do_instance()
  File "/home/ubuntu/tor-browser-crawler/tbcrawler/crawler.py", line 52, in __do_instance
    with self.driver.launch():
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter**
    return self.gen.next()
  File "/home/ubuntu/tor-browser-crawler/tbcrawler/pytbcrawler.py", line 205, in launch
    self.driver = TorBrowserDriver(_self.args, *_self.kwargs)
  File "/home/ubuntu/tor-browser-crawler/src/tbselenium/tbselenium/tbdriver.py", line 68, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 103, in **init**
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in **init**
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 67, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 90, in _start_from_profile_path
    env=self._firefox_env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long

**Comment by mjuarezm** [comment]
Fixed in tor-browser-selenium: https://github.com/webfp/tor-browser-selenium/commit/f0cb807b8e96a285b836d60f8dfd3a9d024f7c28

Also, added a test for it:

https://github.com/webfp/tor-browser-selenium/compare/d2adab3153019b003e917f05a260bda59a60d247...f0cb807b8e96a285b836d60f8dfd3a9d024f7c28
