### ISSUE TITLE
./run_tests.py "Could not find firefox in your system PATH."

### ISSUE THREAD

**Issue by parmegv** [webfp/tor-browser-crawler#4]
vagrant@jessie-amd64:/vagrant/tor-browser-crawler/tor-browser-selenium$ ./run_tests.py /vagrant/tor-browser_en-US
# ......s...s.sssssEE.......EEEEEEEEEE

ERROR: test_screen_capture (test_tbdriver.ScreenshotTest)
## Make sure we can capture the screen.

Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 153, in test_screen_capture
    canvas_exceptions=[cm.CHECK_TPO_URL]) as driver:
  File "tbselenium/tbdriver.py", line 56, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in **init**
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
# 
## ERROR: test_should_fail_with_wrong_sys_socks_port (test_tbdriver.TBDriverFailTest)

Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 121, in test_should_fail_with_wrong_sys_socks_port
    tor_cfg=cm.USE_SYSTEM_TOR) as driver:
  File "tbselenium/tbdriver.py", line 56, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in **init**
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
# 
## ERROR: test_font_bundling (test_tbdriver.TBDriverOptionalArgs)

Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 223, in test_font_bundling
    with TorBrowserDriver(TBB_PATH, tbb_logfile_path=log_file) as driver:
  File "tbselenium/tbdriver.py", line 56, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in **init**
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
# 
## ERROR: test_security_slider_settings_hi (test_tbdriver.TBDriverOptionalArgs)

Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 169, in test_security_slider_settings_hi
    with TorBrowserDriver(TBB_PATH, pref_dict=slider_pref) as driver:
  File "tbselenium/tbdriver.py", line 56, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in **init**
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
# 
## ERROR: test_security_slider_settings_low_mid (test_tbdriver.TBDriverOptionalArgs)

Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 182, in test_security_slider_settings_low_mid
    pref_dict=slider_pref) as driver:
  File "tbselenium/tbdriver.py", line 56, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in **init**
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
# 

ERROR: test_tbb_logfile (test_tbdriver.TBDriverOptionalArgs)
## Make sure log file is populated.

Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 199, in test_tbb_logfile
    with TorBrowserDriver(TBB_PATH, tbb_logfile_path=log_file) as driver:
  File "tbselenium/tbdriver.py", line 56, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in **init**
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
# 

ERROR: test_httpseverywhere (test_tbdriver.TBDriverTest)
## HTTPSEverywhere should redirect to HTTPS version.

Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 36, in setUp
    self.tb_driver = TorBrowserDriver(TBB_PATH)
  File "tbselenium/tbdriver.py", line 56, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in **init**
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
# 

ERROR: test_noscript (test_tbdriver.TBDriverTest)
## NoScript should disable WebGL.

Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 36, in setUp
    self.tb_driver = TorBrowserDriver(TBB_PATH)
  File "tbselenium/tbdriver.py", line 56, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in **init**
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
# 

ERROR: test_tbdriver_profile_not_modified (test_tbdriver.TBDriverTest)
## Visiting a site should not modify the original profile contents.

Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 36, in setUp
    self.tb_driver = TorBrowserDriver(TBB_PATH)
  File "tbselenium/tbdriver.py", line 56, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in **init**
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
# 

ERROR: test_tbdriver_simple_visit (test_tbdriver.TBDriverTest)
## checktor.torproject.org should detect Tor IP.

Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 36, in setUp
    self.tb_driver = TorBrowserDriver(TBB_PATH)
  File "tbselenium/tbdriver.py", line 56, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in **init**
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
# 

ERROR: test_https_everywhere_disabled (test_tbdriver.TBDriverTestAssumptions)
## Make sure the HTTP->HTTPS redirection in the

Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 260, in test_https_everywhere_disabled
    with TorBrowserDriver(TBB_PATH, pref_dict=disable_HE_pref) as driver:
  File "tbselenium/tbdriver.py", line 56, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in **init**
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox
# 

ERROR: test_noscript_webgl_enabled (test_tbdriver.TBDriverTestAssumptions)
## Make sure that when we disable NoScript's WebGL blocking,

Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 275, in test_noscript_webgl_enabled
    pref_dict=disable_NS_webgl_pref) as driver:
  File "tbselenium/tbdriver.py", line 56, in **init**
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in **init**
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

---

Ran 36 tests in 35.725s

FAILED (errors=12, skipped=7)
vagrant@jessie-amd64:/vagrant/tor-browser-crawler/tor-browser-selenium$ find /vagrant/tor-browser_en-US  -name firefox
/vagrant/tor-browser_en-US/Browser/firefox
vagrant@jessie-amd64:/vagrant/tor-browser-crawler/tor-browser-selenium$ date && uname -a
Mon Apr 11 10:09:55 UTC 2016
Linux jessie-amd64 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-2 (2015-04-13) x86_64 GNU/Linux
vagrant@jessie-amd64:/vagrant/tor-browser-crawler/tor-browser-selenium$

**Comment by parmegv** [comment]
This belongs to tor-browser-selenium.

Moved to https://github.com/webfp/tor-browser-selenium/issues/10
